FROM ubuntu:latest

RUN apt-get update && \
  apt-get install -y clamav && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN freshclam

WORKDIR /data

CMD ["clamscan", "--infected", "--recursive", "."]
