#!/usr/bin/env bash

set -euo pipefail

declare -i default_port=5300
backup_resolv_conf=/etc/resolv.conf.backup-setup-host

function die() {
  echo "Fatal: $*" >&2
  exit 1
}

function installed_and_executable() {
  local name
  name="$(command -v "${1}")"

  [[ -n "${name}" ]] && [[ -f "${name}" ]] && [[ -x "${name}" ]]
  return $?
}

function check_deps() {
  deps=(iptables)
  for dep in "${deps[@]}"; do
    installed_and_executable "${dep}" || die "${dep} not installed"
  done
}

function print_help() {
  cat<<END_HELP
Set up iptables rules for Docker dns container

Usage:
  setup-host.sh <-c|-d> [-p 5302]
  setup-host.sh -c -p 5300
  setup-host.sh -d -p 5300
  setup-host.sh -c
  setup-host.sh -h

Options:
  -c    Create rules
  -d    Destroy rules
  -p    Destination port
  -r    Revert /etc/resolv.conf file
  -h    Print this help
END_HELP
}

function set_up_rules() {
  local action="$1"
  local port="$2"
  shift; shift
  local nameservers=( "$@" )

  # no redirection when port 53 is selected
  if [[ "${port}" = 53 ]]; then
    # change /etc/resolv.conf so it contains 127.0.0.1 or revert back when running with -d

    if [[ "${action}" = create ]]; then
      cp /etc/resolv.conf "${backup_resolv_conf}"
      non_nameserver_lines="$(grep --invert-match nameserver /etc/resolv.conf)"
    
      {
        echo "# generated by ./setup-host.sh"
        echo "# backup resolv.conf is in ${backup_resolv_conf}"
        echo "nameserver 127.0.0.1"
        echo "${non_nameserver_lines}"
      } > /etc/resolv.conf
    fi

    if [[ "${action}" = destroy ]]; then
      revert_resolv_conf
    fi
    
    return 0
  fi

  for nameserver in "${nameservers[@]}"; do
    printf "%s: %s\n" "[+] setting redirection for" "${nameserver}"

    if [[ "${action}" = create ]]; then
      iptables -t nat -A OUTPUT -d "${nameserver}" -p udp --dport 53 -j REDIRECT --to-ports "${port}"
    fi

    if [[ "${action}" = destroy ]]; then
      iptables -t nat -D OUTPUT -d "${nameserver}" -p udp --dport 53 -j REDIRECT --to-ports "${port}"
    fi
  done
}

function revert_resolv_conf() {
  if ! [[ -f "${backup_resolv_conf}" ]]; then
    printf "%s\n" "No ${backup_resolv_conf} file, nothing reverted"
    exit 1
  fi

  mv "${backup_resolv_conf}" /etc/resolv.conf
}

function main() {
  check_deps

  if ! [[ "$(id -u)" = 0 ]]; then
    printf "%s\n" "Please run as root"
    exit 1
  fi

  IFS=" " read -r -a nameservers <<< "$(grep -E '^\s{0,}nameserver' /etc/resolv.conf | cut -d' ' -f2 | tr '\n' ' ')"

  action=
  port=${default_port}
  while getopts "cdhp:r" opt; do
    case "${opt}" in
      c)
        action=create
        ;;
      d)
        action=destroy
        ;;
      h)
        print_help
        exit 0
        ;;
      p)
        port="${OPTARG}"
        ;;
      r)
        revert_resolv_conf
        exit 0
        ;;
      *)
        print_help
        exit 1
        ;;
    esac
  done

  if [[ -z "${action}" ]]; then
    printf "%s\n" "Choose either -c or -d"
    exit 1
  fi

  set_up_rules "${action}" "${port}" "${nameservers[@]}"
}

main "$@"
