FROM ubuntu:latest

RUN apt-get update && \
  apt-get install -y clamav && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /data

COPY virusscan.sh /

RUN chmod +x /virusscan.sh

CMD ["/virusscan.sh"]
